# Generated by Django 3.2.15 on 2023-03-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('size', models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL')], default='S', max_length=2)),
                ('type', models.CharField(choices=[('tops', 'Tops'), ('bottoms', 'Bottoms'), ('shoes', 'Shoes'), ('coats', 'Coats')], default='Tops', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('colour', models.CharField(default='Black', max_length=25)),
                ('stock', models.IntegerField(default=1)),
            ],
        ),
    ]
