# Generated by Django 4.1.7 on 2023-03-01 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaCheese',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cheese', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaCrust',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crust', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSauce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sauce', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Pepperoni', models.BooleanField(default=False)),
                ('Chicken', models.BooleanField(default=False)),
                ('Ham', models.BooleanField(default=False)),
                ('Pineapple', models.BooleanField(default=False)),
                ('Peppers', models.BooleanField(default=False)),
                ('Mushrooms', models.BooleanField(default=False)),
                ('Onions', models.BooleanField(default=False)),
                ('cheese', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PizzaOrder.pizzacheese')),
                ('crust', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PizzaOrder.pizzacrust')),
                ('sauce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PizzaOrder.pizzasauce')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PizzaOrder.pizzasize')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('address1', models.CharField(default='', max_length=50)),
                ('address2', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=30)),
                ('county', models.CharField(default='', max_length=30)),
                ('eircode', models.CharField(default='', max_length=7)),
                ('card', models.IntegerField()),
                ('cvv', models.CharField(max_length=3)),
                ('expiry', models.CharField(max_length=5)),
                ('pizza_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PizzaOrder.pizzaorder')),
            ],
        ),
    ]
