# Generated by Django 4.1.7 on 2023-03-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzasize',
            name='size',
            field=models.CharField(choices=[('xsmall', 'Xtra Small (6")'), ('small', 'Small (9")'), ('medium', 'Medium (12")'), ('large', 'Large (15")'), ('xlarge', 'Xtra Large(19")'), ('xxlarge', 'Mega Xtra Large(21")')], default='xsmall', max_length=20),
        ),
    ]
