# Generated by Django 4.1.7 on 2023-03-01 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrder', '0002_alter_pizzasize_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(choices=[('xsmall', 'Xtra Small (6")'), ('small', 'Small (9")'), ('medium', 'Medium (12")'), ('large', 'Large (15")'), ('xlarge', 'Xtra Large(19")'), ('xxlarge', 'Mega Xtra Large(21")')], default='xsmall', max_length=20)),
                ('crust', models.CharField(choices=[('normal', 'Normal'), ('thin', 'Thin'), ('thick', 'Thick'), ('chunky', 'Extra-Thick'), ('glutenfree', 'Gluten-Free')], default='normal', max_length=20)),
                ('sauce', models.CharField(choices=[('Tomato Sauce', 'Tomato Sauce'), ('BBQ Sauce', 'BBQ Sauce'), ('Peri Peri Sauce', 'Peri-Peri Sauce')], default='Tomato Sauce', max_length=20)),
                ('Pepperoni', models.BooleanField(default=False)),
                ('Chicken', models.BooleanField(default=False)),
                ('Ham', models.BooleanField(default=False)),
                ('Pineapple', models.BooleanField(default=False)),
                ('Pepper', models.BooleanField(default=False)),
                ('Mushroom', models.BooleanField(default=False)),
                ('Onion', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='pizzaorder',
            name='Chicken',
        ),
        migrations.RemoveField(
            model_name='pizzaorder',
            name='Ham',
        ),
        migrations.RemoveField(
            model_name='pizzaorder',
            name='Mushrooms',
        ),
        migrations.RemoveField(
            model_name='pizzaorder',
            name='Onions',
        ),
        migrations.RemoveField(
            model_name='pizzaorder',
            name='Pepperoni',
        ),
        migrations.RemoveField(
            model_name='pizzaorder',
            name='Peppers',
        ),
        migrations.RemoveField(
            model_name='pizzaorder',
            name='Pineapple',
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PizzaOrder.pizza'),
        ),
        migrations.DeleteModel(
            name='PizzaSize',
        ),
    ]
