# Generated by Django 4.1.7 on 2023-03-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaOrder', '0004_pizza_cheese'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='Mushroom',
            new_name='Extra_Cheese',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='Onion',
            new_name='Mushrooms',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='Pepper',
            new_name='Onions',
        ),
        migrations.AddField(
            model_name='pizza',
            name='Peppers',
            field=models.BooleanField(default=False),
        ),
    ]
